name: DevSecOps CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Docker Build
        run: |
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME .

      - name: Install Docker Scan
        run: |
          docker scan --version || \
            docker plugin install --grant-all-permissions scanclub/snyk

